name: Sync to S3
on:
  push:
    branches:
      - "*"
jobs:
  create-s3-bucket-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 # replace with your AWS region, e.g., us-east-1

      - name: Get Current Branch Name
        id: branch
        run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Create S3 Bucket
        run: |
          aws s3api create-bucket \
            --bucket ${{ steps.branch.outputs.name }} \
            --region eu-north-1 \
            --create-bucket-configuration LocationConstraint=eu-north-1

      - name: Upload File to S3 Bucket
        run: |
          aws s3 sync . s3://${{ steps.branch.outputs.name }}

      - name: Enable Static Website Hosting
        run: |
          aws s3 website s3://${{ steps.branch.outputs.name }} \
            --index-document index.html

      - name: Make S3 Bucket and Contents Public
        run: |
          aws s3api put-bucket-policy
          --bucket ${{ steps.branch.outputs.name }}
          --policy '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "PublicReadGetObject",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::${{ steps.branch.outputs.name }}/*"
              },
            ]
          }'
